# Generated by Django 3.2.3 on 2021-05-26 19:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('parent_identifier', models.CharField(blank=True, max_length=100)),
                ('path', models.TextField(null=True)),
                ('l', models.IntegerField(null=True)),
                ('r', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='predict.category')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('general_name', models.CharField(blank=True, max_length=200)),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
                ('tz', models.CharField(max_length=30)),
                ('activated', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('edit', 'edit'), ('view', 'view')], default='edit', max_length=4)),
                ('shops', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('user', models.IntegerField(null=True)),
                ('sale_type', models.IntegerField(null=True)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
                ('is_discount', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.client')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(null=True)),
                ('format', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('open_date', models.DateField(null=True)),
                ('area', models.FloatField(blank=True, default=1, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('commodity_credit_days', models.IntegerField(blank=True, default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed', models.BooleanField(default=True)),
                ('pack_capacity', models.PositiveSmallIntegerField(default=1)),
                ('identifier', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('producer', models.IntegerField(null=True)),
                ('article', models.CharField(max_length=100, null=True)),
                ('first_sale', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photo_products')),
                ('barcode', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('categories_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('height', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('width', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('depth', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='predict.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='predict.category')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='predict.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('week_day', models.IntegerField(default=0)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('original_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('stock_total_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.shop')),
            ],
            options={
                'unique_together': {('client', 'dt', 'shop', 'product')},
                'index_together': {('client', 'shop', 'dt')},
            },
        ),
        migrations.CreateModel(
            name='SaleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_updated', models.DateTimeField(auto_now=True)),
                ('api_changed', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predict.sale')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.shop')),
            ],
            options={
                'unique_together': {('client', 'sale', 'shop', 'product')},
            },
        ),
    ]
