# Generated by Django 3.2.3 on 2021-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
