# Generated by Django 3.2.3 on 2021-05-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_category_parent_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.IntegerField(null=True)),
                ('refund', models.IntegerField(null=True)),
                ('order_id', models.IntegerField(null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('original_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('base_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('margin_price_total', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('datetime', models.DateTimeField(null=True)),
                ('datime_open', models.DateTimeField(null=True)),
                ('receipt_items_qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('receipt_total_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_vat', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('total_excise', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.shop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='predict.supplier')),
            ],
        ),
    ]
