# Generated by Django 3.2.3 on 2021-05-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_selling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selling',
            old_name='datime_open',
            new_name='datetime_open',
        ),
    ]
